site_name: Zebrafish Facility Manager Policies and Procedures

nav:
  - Introduction: index.md
  - (C) Management Controls:
      - Risk Assessment Policy: risk_assessment_policy.md
  - (D) Operational Controls:
      - Maintenance Policy: maintenance_policy.md
      - Media Access Policy: media_protection_policy.md
      - Contingency Plan Policy: contingency_plan_policy.md
      - Configuration Management Policy: configuration_management_policy.md
  - (E) Technical Controls:
    - Identification and Authentication: identification_authentication.md
    - Access Control: access_control.md
    - Audit and Accountability: audit_trails.md
  - Risk Assessment Results: risk-assessment-results-2022-02-18.md
  - Contingency Plan: contingency-plan.md

theme:
  name: material
  features:
    - navigation.instant

